name: pokeapi
description: PokeAPI Package
version: 1.0.1
author: Supitsara Prathan <prathanbomb@gmail.com>
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: ">=2.2.0 <3.0.0"

dependencies:
    http: ^0.12.0+1

dev_dependencies:
    test: 1.6.8
